version: '3.7'
networks:
  db:
  backend:
  frontend:
volumes:
  mongo-data:
services:
  mongodb:
    image: mongo:latest
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: always

  mongo-seed:
    build:
      context: .
      dockerfile: Dockerfile.mongo-seed
    networks:
      - db
    depends_on:
      - mongodb

  # If you want to run webapp locally without using docker-compose, 
  # you will also need to run nginx locally and not from docker-compose
  webapp:
    image: bettercollected/webapp
    networks:
      - frontend
    environment:
      INTERNAL_DOCKER_API_ENDPOINT_HOST: http://backend:8000/api/v1
      API_ENDPOINT_HOST: http://localhost:8000/api/v1
      CLIENT_DOMAIN: localhost:3001
      ADMIN_DOMAIN: localhost:3000
      NEXT_PUBLIC_NODE_ENV: development
      ENABLE_TYPEFORM: "true"
      ENABLE_GOOGLE: "true"
    ports:
      - "3000:3000"

  # You need to run nginx only if your webapp is running locally without using docker-compose
  # You may need to setup nginx locally with same configs provided inside `./nginx.conf`
  nginx:
    image: nginx
    networks:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    ports:
      - "80:80"
      - "3001:3001"
      - "3002:3002"

  backend:
    image: bettercollected/backend:latest
    networks:
      - backend
      - db
      - frontend
    environment:
      DEBUG: "false"
      # Api
      API_TITLE: Better Collected Development API
      API_DESCRIPTION: Rest endpoints for bettercollected api
      API_VERSION: 1.0.0
      API_ROOT_PATH: /api/v1
      # Auth
      AUTH_AES_HEX_KEY: agsb0ds6fv-W1vETYfzm98aM-rslaN89I19F-YXvkUA=
      AUTH_JWT_SECRET: J5aMzF0RiPbVKeGcOwqxDt7pL8Uh9nSy
      AUTH_ACCESS_TOKEN_EXPIRY_MINUTES: 1440
      AUTH_REFRESH_TOKEN_EXPIRY_DAYS: 30
      AUTH_BASE_URL: http://auth:8000/api/v1
      AUTH_CALLBACK_URI: http://auth:8000/api/v1/auth/callback
      # Mongo
      MONGO_DB: bettercollected_backend
      MONGO_URI: mongodb://root:root@mongodb:27017
      # Schedular
      SCHEDULAR_INTERVAL_MINUTES: 1
      
      # AWS
      # This is needed to upload workspace profile image and workspace banner image
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      
      # HTTPS API (DEV)
      HTTPS_CERT_API_HOST: 
      HTTPS_CERT_API_KEY: 
    ports:
      - "8000:8000"

  auth:
    image: bettercollected/auth:latest
    networks:
      - backend
      - db
    environment:
      DEBUG: "false"
      # Api
      API_ROOT_PATH: /api/v1
      # Mongo
      MONGO_DB: bettercollected_auth
      MONGO_URI: mongodb://root:root@mongodb:27017
      # Mail
      MAIL_USER: 
      MAIL_PASSWORD: 
      MAIL_SMTP_SERVER: smtp.gmail.com
      MAIL_SMTP_PORT: 58
      MAIL_SENDER: BetterCollected<betatest@sireto.io>
      # Google
      GOOGLE_CLIENT_ID: 
      GOOGLE_PROJECT_ID: 
      GOOGLE_AUTH_URI: https://accounts.google.com/o/oauth2/auth
      GOOGLE_TOKEN_URI: https://oauth2.googleapis.com/token
      GOOGLE_AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
      GOOGLE_CLIENT_SECRET: 
      GOOGLE_REDIRECT_URIS: http://localhost:8000/api/v1/auth/google/basic/callback
      GOOGLE_BASIC_AUTH_REDIRECT: http://localhost:8000/api/v1/auth/google/basic/callback
      GOOGLE_JAVASCRIPT_ORIGINS: http://localhost:3000
      # Typeform
      TYPEFORM_SCOPE: accounts:read
      TYPEFORM_CLIENT_ID: 
      TYPEFORM_CLIENT_SECRET: 
      TYPEFORM_AUTH_URI: https://api.typeform.com/oauth/authorize?state={state}&client_id={client_id}&redirect_uri={redirect_uri}&scope={scope}
      TYPEFORM_TOKEN_URI: https://api.typeform.com/oauth/token
      TYPEFORM_REDIRECT_URI: http://localhost:8000/api/v1/auth/typeform/basic/callback
      TYPEFORM_API_URI: https://api.typeform.com

      # Auth
      AUTH_JWT_SECRET: J5aMzF0RiPbVKeGcOwqxDt7pL8Uh9nSy
      AUTH_AEX_HEX_KEY: agsb0ds6fv-W1vETYfzm98aM-rslaN89I19F-YXvkUA=
      ORGANIZATION_NAME: Better Collected
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1

      # Stripe
      STRIPE_PRODUCT_ID: <ADD_YOUR_OWN>
      STRIPE_SECRET: <ADD_YOUR_OWN>
      STRIPE_WEBHOOK_SECRET: <ADD_YOUR_OWN>
      
      STRIPE_SUCCESS_URL: http://localhost:3000/refresh-token
      STRIPE_CANCEL_URL: http://localhost:3000/refresh-token
      STRIPE_RETURN_URL: http://localhost:3000/refresh-token
      CLIENT_ADMIN_URL: http://localhost:3000
    ports:
      - "8001:8000"

  stripe-webhook:
    image: stripe/stripe-cli:latest
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "stripe login && stripe listen --forward-to backend:8000/api/v1/stripe/webhooks"
    networks:
      - backend
    depends_on:
      - backend

  integrations-typeform:
    image: bettercollected/integrations-typeform:latest
    networks:
      - backend
      - db
    environment:
      DEBUG: "false"
      # Api
      API_ROOT_PATH: /api/v1
      #Auth
      AUTH_JWT_SECRET: J5aMzF0RiPbVKeGcOwqxDt7pL8Uh9nSy
      # Mongo
      MONGO_DB: bettercollected_typeform
      MONGO_URI: mongodb://root:root@mongodb:27017
      # Typeform
      TYPEFORM_SCOPE: offline+accounts:read+forms:read+responses:read
      TYPEFORM_CLIENT_ID: 
      TYPEFORM_CLIENT_SECRET: 
      TYPEFORM_AUTH_URI: https://api.typeform.com/oauth/authorize?state={state}&client_id={client_id}&redirect_uri={redirect_uri}&scope={scope}
      TYPEFORM_TOKEN_URI: https://api.typeform.com/oauth/token
      TYPEFORM_REDIRECT_URI: https://localhost:8000/api/v1/auth/typeform/oauth/callback
      TYPEFORM_API_URI: https://api.typeform.com
    ports:
      - "8002:8000"

  integrations-googleform:
    image: bettercollected/integrations-googleform:latest
    networks:
      - backend
      - db
    environment:
      DEBUG: "false"
      AUTH_JWT_SECRET: J5aMzF0RiPbVKeGcOwqxDt7pL8Uh9nSy
      GOOGLE_AES_KEY: agsb0ds6fv-W1vETYfzm98aM-rslaN89I19F-YXvkUA=
      API_ROOT_PATH: /api/v1
      # Mongo
      MONGO_DB: bettercollected_googleform
      MONGO_URI: mongodb://root:root@mongodb:27017
      # Google
      GOOGLE_CLIENT_TYPE: web
      GOOGLE_CLIENT_ID: 
      GOOGLE_PROJECT_ID: 
      GOOGLE_CLIENT_SECRET: 
      GOOGLE_AUTH_URI: https://accounts.google.com/o/oauth2/auth
      GOOGLE_TOKEN_URI: https://oauth2.googleapis.com/token
      GOOGLE_AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
      GOOGLE_REDIRECT_URIS: http://localhost:8000/api/v1/auth/google/oauth/callback
      GOOGLE_JAVASCRIPT_ORIGINS: http://localhost:3000,http://localhost:3001
      GOOGLE_SCOPES: "openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/forms.body.readonly https://www.googleapis.com/auth/forms.responses.readonly"
      GOOGLE_API_SERVICE_NAME: drive
      GOOGLE_API_VERSION: v2
      GOOGLE_REVOKE_CREDENTIALS_URL: https://oauth2.googleapis.com/revoke
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
    ports:
      - "8003:8000"
